Repository Global-Students/global-students-server, pull requests merged in 2024-02, with the labels that each got.

#93 #92 [MODIFY] 게시판 국가,학교 매핑 완료
  src/main/java/com/example/globalStudents/domain/board/entity/BoardEntity.java
  src/main/java/com/example/globalStudents/domain/user/entity/CountryEntity.java
  src/main/java/com/example/globalStudents/domain/user/entity/UniversityEntity.java
Labels: 진형, modify

#97 #96 [FEAT] refreshToken 추가 기능 구현 완료
  src/main/java/com/example/globalStudents/domain/user/controller/AuthController.java
  src/main/java/com/example/globalStudents/domain/user/service/UserService.java
  src/main/java/com/example/globalStudents/domain/user/service/UserServiceImpl.java
  src/main/java/com/example/globalStudents/global/auth/filter/LoginFilter.java
  src/main/java/com/example/globalStudents/global/util/JWTUtil.java
Labels: feat, 범수

#105 #104 [FEAT] 유저 인증 및 정지 관리자 페이지 기능 구현 완료
  src/main/java/com/example/globalStudents/domain/admin/user/controller/AdminUserController.java
  src/main/java/com/example/globalStudents/domain/admin/user/converter/AdminConverterImpl.java
  src/main/java/com/example/globalStudents/domain/admin/user/service/AdminUserService.java
  src/main/java/com/example/globalStudents/domain/admin/user/service/AdminUserServiceImpl.java
  src/main/java/com/example/globalStudents/domain/user/dto/UserResponseDTO.java
  src/main/java/com/example/globalStudents/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/globalStudents/global/auth/SecurityConfig.java
  src/main/java/com/example/globalStudents/global/auth/filter/LoginFilter.java
  src/main/java/com/example/globalStudents/global/auth/jwt/CustomUserDetails.java
Labels: feat, 범수

#107 #106 [FIX] access token 로그아웃 버그 해결
  src/main/java/com/example/globalStudents/domain/user/controller/AuthController.java
  src/main/java/com/example/globalStudents/domain/user/service/UserService.java
  src/main/java/com/example/globalStudents/domain/user/service/UserServiceImpl.java
Labels: 범수, fix

#110 #109 [FEAT] 게시글 이미지 업로드 AWS S3 연결 완료
  src/main/java/com/example/globalStudents/domain/board/controller/BoardController.java
  src/main/java/com/example/globalStudents/domain/board/converter/PostImageConverter.java
  src/main/java/com/example/globalStudents/domain/board/entity/PostImageEntity.java
  src/main/java/com/example/globalStudents/domain/board/service/PostImageService.java
  src/main/java/com/example/globalStudents/domain/board/service/PostImageServiceImpl.java
  src/main/java/com/example/globalStudents/global/util/S3Util.java
Labels: feat, 진형

#116 #115 [REFACTOR] BoardController Entity 노출 수정 완료
  src/main/java/com/example/globalStudents/domain/board/controller/BoardController.java
  src/main/java/com/example/globalStudents/domain/board/service/CommentService.java
  src/main/java/com/example/globalStudents/domain/board/service/CommentServiceImpl.java
  src/main/java/com/example/globalStudents/domain/board/service/PostService.java
  src/main/java/com/example/globalStudents/domain/board/service/PostServiceImpl.java
  src/main/java/com/example/globalStudents/domain/board/service/ReportService.java
  src/main/java/com/example/globalStudents/domain/board/service/ReportServiceImpl.java
Labels: 진형, refactor

#118 #117 [FEAT] 학교 서류 S3 업로드 구현 완료
  src/main/java/com/example/globalStudents/domain/myPage/entity/UserImageEntity.java
  src/main/java/com/example/globalStudents/domain/user/controller/AuthController.java
  src/main/java/com/example/globalStudents/domain/user/converter/UserConverterImpl.java
  src/main/java/com/example/globalStudents/domain/user/enums/UserRole.java
  src/main/java/com/example/globalStudents/domain/user/service/UserServiceImpl.java
  src/main/java/com/example/globalStudents/global/auth/SecurityConfig.java
Labels: feat, 범수
